name: elements_app
description: Periodic Table - Learn and explore chemical elements
publish_to: 'none'
version: 1.0.1+4

environment:
  sdk: '>=3.8.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Network
  http: ^1.1.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1

  # State Management
  provider: ^6.0.5
  
  # Storage
  shared_preferences: ^2.2.2

  # Analysis
  very_good_analysis: ^5.1.0

  # UI 
  lottie: ^2.6.0
  flutter_svg: ^2.0.7
  animated_button: ^0.2.0
  like_button: ^2.0.5
  neon_widgets: ^2.0.0
  percent_indicator: ^4.2.3  
  # Network 
  connectivity_plus: ^5.0.1

  # Ads
  google_mobile_ads: ^6.0.0
  
  # Firebase
  firebase_core: ^2.21.0

  # Rating
  flutter_rating_bar: ^4.0.1
  in_app_review: ^2.0.9

  # Device Preview
  device_preview: ^1.1.0
  home_widget: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Code Generation
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

  # Launcher
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.4

  # General
  change_app_package_name: ^1.1.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/remove-bg-logo.png"
  min_sdk_android: 21 
  adaptive_icon_background: "#212437"
  adaptive_icon_foreground: "assets/img/play_store_512.png"

flutter_native_splash:
  android: true
  ios: true 
  color: "#212437"
  image: assets/img/small-launch-ic.png
  color_dark: "#212437"
  color_android: "#212437"
  color_dark_android: "#212437"
  android_12:
    color: "#212437"
    image: assets/img/small-launch-ic.png
    color_dark: "#212437"
 


flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/svg/
    - assets/img/

